default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>

development:
  primary:
    <<: *default
    database: villagerhub_development
  cable:
    <<: *default
    database: villagerhub_development_cable

test:
  primary:
    <<: *default
    database: villagerhub_test
  cable:
    <<: *default
    database: villagerhub_test_cable

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cable:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>